# Generated by Django 3.2.5 on 2021-08-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prcomment',
            old_name='date',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='prcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.pr'),
        ),
    ]
