# Generated by Django 3.2.5 on 2021-08-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_graduate_information_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
