# Generated by Django 3.2.5 on 2021-08-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='information',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='pr',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.CreateModel(
            name='Pr_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.pr')),
            ],
        ),
        migrations.CreateModel(
            name='Info_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.information')),
            ],
        ),
        migrations.CreateModel(
            name='Grad_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_grad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.graduate')),
            ],
        ),
    ]
