# Generated by Django 3.2.5 on 2021-08-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20210814_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradcomment',
            old_name='created_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='infocomment',
            old_name='created_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='prcomment',
            old_name='created_on',
            new_name='date',
        ),
    ]
